/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.parser;

import entitiesdb.language.lexer.*;
import entitiesdb.language.node.*;
import entitiesdb.language.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AQueryMain */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce AAapproxmain1Main */
		    {
			ArrayList list = new1();
			push(goTo(0), list, false);
		    }
		    break;
                    case 2: /* reduce AAapproxmain2Main */
		    {
			ArrayList list = new2();
			push(goTo(0), list, false);
		    }
		    break;
                    case 3: /* reduce AAinsertmain1Main */
		    {
			ArrayList list = new3();
			push(goTo(0), list, false);
		    }
		    break;
                    case 4: /* reduce AAinsertmain2Main */
		    {
			ArrayList list = new4();
			push(goTo(0), list, false);
		    }
		    break;
                    case 5: /* reduce AAsimplequery1Query */
		    {
			ArrayList list = new5();
			push(goTo(1), list, false);
		    }
		    break;
                    case 6: /* reduce AAsimplequery2Query */
		    {
			ArrayList list = new6();
			push(goTo(1), list, false);
		    }
		    break;
                    case 7: /* reduce AAsimplequery3Query */
		    {
			ArrayList list = new7();
			push(goTo(1), list, false);
		    }
		    break;
                    case 8: /* reduce AAsimplequery4Query */
		    {
			ArrayList list = new8();
			push(goTo(1), list, false);
		    }
		    break;
                    case 9: /* reduce AAcomplexquery1Query */
		    {
			ArrayList list = new9();
			push(goTo(1), list, false);
		    }
		    break;
                    case 10: /* reduce AAcomplexquery2Query */
		    {
			ArrayList list = new10();
			push(goTo(1), list, false);
		    }
		    break;
                    case 11: /* reduce AAcomplexquery3Query */
		    {
			ArrayList list = new11();
			push(goTo(1), list, false);
		    }
		    break;
                    case 12: /* reduce AAcomplexquery4Query */
		    {
			ArrayList list = new12();
			push(goTo(1), list, false);
		    }
		    break;
                    case 13: /* reduce AHead */
		    {
			ArrayList list = new13();
			push(goTo(2), list, false);
		    }
		    break;
                    case 14: /* reduce ASingleBody */
		    {
			ArrayList list = new14();
			push(goTo(3), list, false);
		    }
		    break;
                    case 15: /* reduce AListBody */
		    {
			ArrayList list = new15();
			push(goTo(3), list, false);
		    }
		    break;
                    case 16: /* reduce AEntitypattern */
		    {
			ArrayList list = new16();
			push(goTo(4), list, false);
		    }
		    break;
                    case 17: /* reduce AIdeEntitytype */
		    {
			ArrayList list = new17();
			push(goTo(5), list, false);
		    }
		    break;
                    case 18: /* reduce AVariableEntitytype */
		    {
			ArrayList list = new18();
			push(goTo(5), list, false);
		    }
		    break;
                    case 19: /* reduce AEntitybody */
		    {
			ArrayList list = new19();
			push(goTo(6), list, false);
		    }
		    break;
                    case 20: /* reduce ASingleAttributes */
		    {
			ArrayList list = new20();
			push(goTo(7), list, false);
		    }
		    break;
                    case 21: /* reduce AListAttributes */
		    {
			ArrayList list = new21();
			push(goTo(7), list, false);
		    }
		    break;
                    case 22: /* reduce AAttribute */
		    {
			ArrayList list = new22();
			push(goTo(8), list, false);
		    }
		    break;
                    case 23: /* reduce AIdeAttributetype */
		    {
			ArrayList list = new23();
			push(goTo(9), list, false);
		    }
		    break;
                    case 24: /* reduce AVariableAttributetype */
		    {
			ArrayList list = new24();
			push(goTo(9), list, false);
		    }
		    break;
                    case 25: /* reduce AStringValue */
		    {
			ArrayList list = new25();
			push(goTo(10), list, false);
		    }
		    break;
                    case 26: /* reduce AEntityValue */
		    {
			ArrayList list = new26();
			push(goTo(10), list, false);
		    }
		    break;
                    case 27: /* reduce AVariableValue */
		    {
			ArrayList list = new27();
			push(goTo(10), list, false);
		    }
		    break;
                    case 28: /* reduce ABodyValue */
		    {
			ArrayList list = new28();
			push(goTo(10), list, false);
		    }
		    break;
                    case 29: /* reduce ADesOrderby */
		    {
			ArrayList list = new29();
			push(goTo(11), list, false);
		    }
		    break;
                    case 30: /* reduce AAscOrderby */
		    {
			ArrayList list = new30();
			push(goTo(11), list, false);
		    }
		    break;
                    case 31: /* reduce ASingleConditions */
		    {
			ArrayList list = new31();
			push(goTo(12), list, false);
		    }
		    break;
                    case 32: /* reduce AListConditions */
		    {
			ArrayList list = new32();
			push(goTo(12), list, false);
		    }
		    break;
                    case 33: /* reduce AEqualCondition */
		    {
			ArrayList list = new33();
			push(goTo(13), list, false);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PMain node1 = (PMain) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AQueryMain */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMain pmainNode1;
        {
            // Block
        PQuery pqueryNode2;
        pqueryNode2 = (PQuery)nodeArrayList1.get(0);

        pmainNode1 = new AQueryMain(pqueryNode2);
        }
	nodeList.add(pmainNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce AAapproxmain1Main */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMain pmainNode1;
        {
            // Block
        TPercent tpercentNode2;
        TVariable tvariableNode3;
        TDefinedby tdefinedbyNode4;
        PEntitypattern pentitypatternNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        tpercentNode2 = (TPercent)nodeArrayList1.get(0);
        tvariableNode3 = (TVariable)nodeArrayList2.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList3.get(0);
        pentitypatternNode5 = (PEntitypattern)nodeArrayList4.get(0);

        pmainNode1 = new AApproxMain(tpercentNode2, tvariableNode3, tdefinedbyNode4, pentitypatternNode5, null);
        }
	nodeList.add(pmainNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AAapproxmain2Main */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMain pmainNode1;
        {
            // Block
        TPercent tpercentNode2;
        TVariable tvariableNode3;
        TDefinedby tdefinedbyNode4;
        PEntitypattern pentitypatternNode5;
        TNumber tnumberNode6;
        tpercentNode2 = (TPercent)nodeArrayList1.get(0);
        tvariableNode3 = (TVariable)nodeArrayList2.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList3.get(0);
        pentitypatternNode5 = (PEntitypattern)nodeArrayList4.get(0);
        tnumberNode6 = (TNumber)nodeArrayList5.get(0);

        pmainNode1 = new AApproxMain(tpercentNode2, tvariableNode3, tdefinedbyNode4, pentitypatternNode5, tnumberNode6);
        }
	nodeList.add(pmainNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AAinsertmain1Main */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMain pmainNode1;
        {
            // Block
        TLess tlessNode2;
        TIdentifier tidentifierNode3;
        @SuppressWarnings("unused") Object nullNode4 = null;
        tlessNode2 = (TLess)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);

        pmainNode1 = new AInsertMain(tlessNode2, tidentifierNode3, null);
        }
	nodeList.add(pmainNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce AAinsertmain2Main */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PMain pmainNode1;
        {
            // Block
        TLess tlessNode2;
        TIdentifier tidentifierNode3;
        PEntitybody pentitybodyNode4;
        tlessNode2 = (TLess)nodeArrayList1.get(0);
        tidentifierNode3 = (TIdentifier)nodeArrayList2.get(0);
        pentitybodyNode4 = (PEntitybody)nodeArrayList3.get(0);

        pmainNode1 = new AInsertMain(tlessNode2, tidentifierNode3, pentitybodyNode4);
        }
	nodeList.add(pmainNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce AAsimplequery1Query */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        PHead pheadNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        TDefinedby tdefinedbyNode4;
        PBody pbodyNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        pheadNode2 = (PHead)nodeArrayList1.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList2.get(0);
        pbodyNode5 = (PBody)nodeArrayList3.get(0);

        pqueryNode1 = new ASimpleQuery(pheadNode2, null, tdefinedbyNode4, pbodyNode5, null);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce AAsimplequery2Query */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        PHead pheadNode2;
        TExcmark texcmarkNode3;
        TDefinedby tdefinedbyNode4;
        PBody pbodyNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        pheadNode2 = (PHead)nodeArrayList1.get(0);
        texcmarkNode3 = (TExcmark)nodeArrayList2.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList3.get(0);
        pbodyNode5 = (PBody)nodeArrayList4.get(0);

        pqueryNode1 = new ASimpleQuery(pheadNode2, texcmarkNode3, tdefinedbyNode4, pbodyNode5, null);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AAsimplequery3Query */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        PHead pheadNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        TDefinedby tdefinedbyNode4;
        PBody pbodyNode5;
        POrderby porderbyNode6;
        pheadNode2 = (PHead)nodeArrayList1.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList2.get(0);
        pbodyNode5 = (PBody)nodeArrayList3.get(0);
        porderbyNode6 = (POrderby)nodeArrayList4.get(0);

        pqueryNode1 = new ASimpleQuery(pheadNode2, null, tdefinedbyNode4, pbodyNode5, porderbyNode6);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce AAsimplequery4Query */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        PHead pheadNode2;
        TExcmark texcmarkNode3;
        TDefinedby tdefinedbyNode4;
        PBody pbodyNode5;
        POrderby porderbyNode6;
        pheadNode2 = (PHead)nodeArrayList1.get(0);
        texcmarkNode3 = (TExcmark)nodeArrayList2.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList3.get(0);
        pbodyNode5 = (PBody)nodeArrayList4.get(0);
        porderbyNode6 = (POrderby)nodeArrayList5.get(0);

        pqueryNode1 = new ASimpleQuery(pheadNode2, texcmarkNode3, tdefinedbyNode4, pbodyNode5, porderbyNode6);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce AAcomplexquery1Query */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        PHead pheadNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        TDefinedby tdefinedbyNode4;
        PBody pbodyNode5;
        TQmark tqmarkNode6;
        PConditions pconditionsNode7;
        @SuppressWarnings("unused") Object nullNode8 = null;
        pheadNode2 = (PHead)nodeArrayList1.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList2.get(0);
        pbodyNode5 = (PBody)nodeArrayList3.get(0);
        tqmarkNode6 = (TQmark)nodeArrayList4.get(0);
        pconditionsNode7 = (PConditions)nodeArrayList5.get(0);

        pqueryNode1 = new AComplexQuery(pheadNode2, null, tdefinedbyNode4, pbodyNode5, tqmarkNode6, pconditionsNode7, null);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new10() /* reduce AAcomplexquery2Query */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        PHead pheadNode2;
        TExcmark texcmarkNode3;
        TDefinedby tdefinedbyNode4;
        PBody pbodyNode5;
        TQmark tqmarkNode6;
        PConditions pconditionsNode7;
        @SuppressWarnings("unused") Object nullNode8 = null;
        pheadNode2 = (PHead)nodeArrayList1.get(0);
        texcmarkNode3 = (TExcmark)nodeArrayList2.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList3.get(0);
        pbodyNode5 = (PBody)nodeArrayList4.get(0);
        tqmarkNode6 = (TQmark)nodeArrayList5.get(0);
        pconditionsNode7 = (PConditions)nodeArrayList6.get(0);

        pqueryNode1 = new AComplexQuery(pheadNode2, texcmarkNode3, tdefinedbyNode4, pbodyNode5, tqmarkNode6, pconditionsNode7, null);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new11() /* reduce AAcomplexquery3Query */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        PHead pheadNode2;
        @SuppressWarnings("unused") Object nullNode3 = null;
        TDefinedby tdefinedbyNode4;
        PBody pbodyNode5;
        TQmark tqmarkNode6;
        PConditions pconditionsNode7;
        POrderby porderbyNode8;
        pheadNode2 = (PHead)nodeArrayList1.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList2.get(0);
        pbodyNode5 = (PBody)nodeArrayList3.get(0);
        tqmarkNode6 = (TQmark)nodeArrayList4.get(0);
        pconditionsNode7 = (PConditions)nodeArrayList5.get(0);
        porderbyNode8 = (POrderby)nodeArrayList6.get(0);

        pqueryNode1 = new AComplexQuery(pheadNode2, null, tdefinedbyNode4, pbodyNode5, tqmarkNode6, pconditionsNode7, porderbyNode8);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new12() /* reduce AAcomplexquery4Query */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PQuery pqueryNode1;
        {
            // Block
        PHead pheadNode2;
        TExcmark texcmarkNode3;
        TDefinedby tdefinedbyNode4;
        PBody pbodyNode5;
        TQmark tqmarkNode6;
        PConditions pconditionsNode7;
        POrderby porderbyNode8;
        pheadNode2 = (PHead)nodeArrayList1.get(0);
        texcmarkNode3 = (TExcmark)nodeArrayList2.get(0);
        tdefinedbyNode4 = (TDefinedby)nodeArrayList3.get(0);
        pbodyNode5 = (PBody)nodeArrayList4.get(0);
        tqmarkNode6 = (TQmark)nodeArrayList5.get(0);
        pconditionsNode7 = (PConditions)nodeArrayList6.get(0);
        porderbyNode8 = (POrderby)nodeArrayList7.get(0);

        pqueryNode1 = new AComplexQuery(pheadNode2, texcmarkNode3, tdefinedbyNode4, pbodyNode5, tqmarkNode6, pconditionsNode7, porderbyNode8);
        }
	nodeList.add(pqueryNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new13() /* reduce AHead */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PHead pheadNode1;
        {
            // Block
        PEntitytype pentitytypeNode2;
        PEntitybody pentitybodyNode3;
        pentitytypeNode2 = (PEntitytype)nodeArrayList1.get(0);
        pentitybodyNode3 = (PEntitybody)nodeArrayList2.get(0);

        pheadNode1 = new AHead(pentitytypeNode2, pentitybodyNode3);
        }
	nodeList.add(pheadNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new14() /* reduce ASingleBody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBody pbodyNode1;
        {
            // Block
        PEntitypattern pentitypatternNode2;
        pentitypatternNode2 = (PEntitypattern)nodeArrayList1.get(0);

        pbodyNode1 = new ASingleBody(pentitypatternNode2);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new15() /* reduce AListBody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PBody pbodyNode1;
        {
            // Block
        PBody pbodyNode2;
        TComa tcomaNode3;
        PEntitypattern pentitypatternNode4;
        pbodyNode2 = (PBody)nodeArrayList1.get(0);
        tcomaNode3 = (TComa)nodeArrayList2.get(0);
        pentitypatternNode4 = (PEntitypattern)nodeArrayList3.get(0);

        pbodyNode1 = new AListBody(pbodyNode2, tcomaNode3, pentitypatternNode4);
        }
	nodeList.add(pbodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new16() /* reduce AEntitypattern */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PEntitypattern pentitypatternNode1;
        {
            // Block
        PEntitytype pentitytypeNode2;
        PEntitybody pentitybodyNode3;
        pentitytypeNode2 = (PEntitytype)nodeArrayList1.get(0);
        pentitybodyNode3 = (PEntitybody)nodeArrayList2.get(0);

        pentitypatternNode1 = new AEntitypattern(pentitytypeNode2, pentitybodyNode3);
        }
	nodeList.add(pentitypatternNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new17() /* reduce AIdeEntitytype */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PEntitytype pentitytypeNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        pentitytypeNode1 = new AIdeEntitytype(tidentifierNode2);
        }
	nodeList.add(pentitytypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new18() /* reduce AVariableEntitytype */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PEntitytype pentitytypeNode1;
        {
            // Block
        TVariable tvariableNode2;
        tvariableNode2 = (TVariable)nodeArrayList1.get(0);

        pentitytypeNode1 = new AVariableEntitytype(tvariableNode2);
        }
	nodeList.add(pentitytypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new19() /* reduce AEntitybody */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PEntitybody pentitybodyNode1;
        {
            // Block
        TLbracket tlbracketNode2;
        PAttributes pattributesNode3;
        TRbracket trbracketNode4;
        tlbracketNode2 = (TLbracket)nodeArrayList1.get(0);
        pattributesNode3 = (PAttributes)nodeArrayList2.get(0);
        trbracketNode4 = (TRbracket)nodeArrayList3.get(0);

        pentitybodyNode1 = new AEntitybody(tlbracketNode2, pattributesNode3, trbracketNode4);
        }
	nodeList.add(pentitybodyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new20() /* reduce ASingleAttributes */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAttributes pattributesNode1;
        {
            // Block
        PAttribute pattributeNode2;
        pattributeNode2 = (PAttribute)nodeArrayList1.get(0);

        pattributesNode1 = new ASingleAttributes(pattributeNode2);
        }
	nodeList.add(pattributesNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new21() /* reduce AListAttributes */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAttributes pattributesNode1;
        {
            // Block
        PAttributes pattributesNode2;
        TComa tcomaNode3;
        PAttribute pattributeNode4;
        pattributesNode2 = (PAttributes)nodeArrayList1.get(0);
        tcomaNode3 = (TComa)nodeArrayList2.get(0);
        pattributeNode4 = (PAttribute)nodeArrayList3.get(0);

        pattributesNode1 = new AListAttributes(pattributesNode2, tcomaNode3, pattributeNode4);
        }
	nodeList.add(pattributesNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new22() /* reduce AAttribute */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAttribute pattributeNode1;
        {
            // Block
        PAttributetype pattributetypeNode2;
        TColon tcolonNode3;
        PValue pvalueNode4;
        pattributetypeNode2 = (PAttributetype)nodeArrayList1.get(0);
        tcolonNode3 = (TColon)nodeArrayList2.get(0);
        pvalueNode4 = (PValue)nodeArrayList3.get(0);

        pattributeNode1 = new AAttribute(pattributetypeNode2, tcolonNode3, pvalueNode4);
        }
	nodeList.add(pattributeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new23() /* reduce AIdeAttributetype */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAttributetype pattributetypeNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        pattributetypeNode1 = new AIdeAttributetype(tidentifierNode2);
        }
	nodeList.add(pattributetypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new24() /* reduce AVariableAttributetype */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PAttributetype pattributetypeNode1;
        {
            // Block
        TVariable tvariableNode2;
        tvariableNode2 = (TVariable)nodeArrayList1.get(0);

        pattributetypeNode1 = new AVariableAttributetype(tvariableNode2);
        }
	nodeList.add(pattributetypeNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new25() /* reduce AStringValue */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PValue pvalueNode1;
        {
            // Block
        TString tstringNode2;
        tstringNode2 = (TString)nodeArrayList1.get(0);

        pvalueNode1 = new AStringValue(tstringNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new26() /* reduce AEntityValue */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PValue pvalueNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);

        pvalueNode1 = new AEntityValue(tidentifierNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new27() /* reduce AVariableValue */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PValue pvalueNode1;
        {
            // Block
        TVariable tvariableNode2;
        tvariableNode2 = (TVariable)nodeArrayList1.get(0);

        pvalueNode1 = new AVariableValue(tvariableNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new28() /* reduce ABodyValue */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PValue pvalueNode1;
        {
            // Block
        PEntitypattern pentitypatternNode2;
        pentitypatternNode2 = (PEntitypattern)nodeArrayList1.get(0);

        pvalueNode1 = new ABodyValue(pentitypatternNode2);
        }
	nodeList.add(pvalueNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new29() /* reduce ADesOrderby */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        POrderby porderbyNode1;
        {
            // Block
        TPipe tpipeNode2;
        TVariable tvariableNode3;
        TMinus tminusNode4;
        tpipeNode2 = (TPipe)nodeArrayList1.get(0);
        tvariableNode3 = (TVariable)nodeArrayList2.get(0);
        tminusNode4 = (TMinus)nodeArrayList3.get(0);

        porderbyNode1 = new ADesOrderby(tpipeNode2, tvariableNode3, tminusNode4);
        }
	nodeList.add(porderbyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new30() /* reduce AAscOrderby */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        POrderby porderbyNode1;
        {
            // Block
        TPipe tpipeNode2;
        TVariable tvariableNode3;
        TPlus tplusNode4;
        tpipeNode2 = (TPipe)nodeArrayList1.get(0);
        tvariableNode3 = (TVariable)nodeArrayList2.get(0);
        tplusNode4 = (TPlus)nodeArrayList3.get(0);

        porderbyNode1 = new AAscOrderby(tpipeNode2, tvariableNode3, tplusNode4);
        }
	nodeList.add(porderbyNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new31() /* reduce ASingleConditions */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PConditions pconditionsNode1;
        {
            // Block
        PCondition pconditionNode2;
        pconditionNode2 = (PCondition)nodeArrayList1.get(0);

        pconditionsNode1 = new ASingleConditions(pconditionNode2);
        }
	nodeList.add(pconditionsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new32() /* reduce AListConditions */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PConditions pconditionsNode1;
        {
            // Block
        PCondition pconditionNode2;
        TComa tcomaNode3;
        PConditions pconditionsNode4;
        pconditionNode2 = (PCondition)nodeArrayList1.get(0);
        tcomaNode3 = (TComa)nodeArrayList2.get(0);
        pconditionsNode4 = (PConditions)nodeArrayList3.get(0);

        pconditionsNode1 = new AListConditions(pconditionNode2, tcomaNode3, pconditionsNode4);
        }
	nodeList.add(pconditionsNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new33() /* reduce AEqualCondition */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PCondition pconditionNode1;
        {
            // Block
        TVariable tvariableNode2;
        TEqual tequalNode3;
        PValue pvalueNode4;
        tvariableNode2 = (TVariable)nodeArrayList1.get(0);
        tequalNode3 = (TEqual)nodeArrayList2.get(0);
        pvalueNode4 = (PValue)nodeArrayList3.get(0);

        pconditionNode1 = new AEqualCondition(tvariableNode2, tequalNode3, pvalueNode4);
        }
	nodeList.add(pconditionNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {5, SHIFT, 1}, {6, SHIFT, 2}, {10, SHIFT, 3}, {17, SHIFT, 4}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 3}, {6, SHIFT, 9}, },
			{{-1, ERROR, 4}, {5, SHIFT, 10}, },
			{{-1, ERROR, 5}, {18, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 7}, {2, SHIFT, 11}, {11, SHIFT, 12}, },
			{{-1, ERROR, 8}, {3, SHIFT, 13}, },
			{{-1, ERROR, 9}, {2, SHIFT, 15}, },
			{{-1, REDUCE, 3}, {3, SHIFT, 13}, },
			{{-1, ERROR, 11}, {5, SHIFT, 1}, {6, SHIFT, 2}, },
			{{-1, ERROR, 12}, {2, SHIFT, 20}, },
			{{-1, ERROR, 13}, {5, SHIFT, 21}, {6, SHIFT, 22}, },
			{{-1, REDUCE, 13}, },
			{{-1, ERROR, 15}, {5, SHIFT, 1}, {6, SHIFT, 2}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 5}, {0, SHIFT, 27}, {9, SHIFT, 28}, {12, SHIFT, 29}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 19}, {3, SHIFT, 13}, },
			{{-1, ERROR, 20}, {5, SHIFT, 1}, {6, SHIFT, 2}, },
			{{-1, REDUCE, 23}, },
			{{-1, REDUCE, 24}, },
			{{-1, ERROR, 23}, {0, SHIFT, 33}, {4, SHIFT, 34}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 25}, {1, SHIFT, 35}, },
			{{-1, REDUCE, 1}, {8, SHIFT, 36}, },
			{{-1, ERROR, 27}, {5, SHIFT, 1}, {6, SHIFT, 2}, },
			{{-1, ERROR, 28}, {6, SHIFT, 38}, },
			{{-1, ERROR, 29}, {6, SHIFT, 41}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 6}, {0, SHIFT, 27}, {9, SHIFT, 42}, {12, SHIFT, 29}, },
			{{-1, ERROR, 33}, {5, SHIFT, 21}, {6, SHIFT, 22}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 35}, {5, SHIFT, 45}, {6, SHIFT, 46}, {7, SHIFT, 47}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 15}, },
			{{-1, ERROR, 38}, {15, SHIFT, 50}, },
			{{-1, REDUCE, 9}, {12, SHIFT, 29}, },
			{{-1, REDUCE, 31}, {0, SHIFT, 52}, },
			{{-1, ERROR, 41}, {13, SHIFT, 53}, {14, SHIFT, 54}, },
			{{-1, ERROR, 42}, {6, SHIFT, 38}, },
			{{-1, REDUCE, 8}, },
			{{-1, REDUCE, 21}, },
			{{-1, REDUCE, 26}, {3, REDUCE, 17}, },
			{{-1, REDUCE, 27}, {3, REDUCE, 18}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 28}, },
			{{-1, REDUCE, 22}, },
			{{-1, ERROR, 50}, {5, SHIFT, 45}, {6, SHIFT, 46}, {7, SHIFT, 47}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 52}, {6, SHIFT, 38}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 29}, },
			{{-1, REDUCE, 10}, {12, SHIFT, 29}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 32}, },
			{{-1, REDUCE, 12}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 5}, },
			{{-1, 6}, },
			{{-1, 7}, },
			{{-1, 17}, {20, 32}, },
			{{-1, 18}, {15, 26}, {27, 37}, {35, 48}, {50, 48}, },
			{{-1, 19}, {0, 8}, },
			{{-1, 14}, {10, 16}, {19, 31}, },
			{{-1, 23}, },
			{{-1, 24}, {33, 44}, },
			{{-1, 25}, },
			{{-1, 49}, {50, 56}, },
			{{-1, 30}, {32, 43}, {39, 51}, {55, 58}, },
			{{-1, 39}, {42, 55}, {52, 57}, },
			{{-1, 40}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: identifier, variable, '%', '<'",
			"expecting: '('",
			"expecting: variable",
			"expecting: identifier",
			"expecting: EOF",
			"expecting: ':-', '!'",
			"expecting: ':-'",
			"expecting: '(', EOF",
			"expecting: identifier, variable",
			"expecting: ',', '?', '|', EOF",
			"expecting: ':'",
			"expecting: ',', ')'",
			"expecting: number, EOF",
			"expecting: ',', ')', number, '?', '|', EOF",
			"expecting: ',', ':-', ')', number, '?', '!', '|', EOF",
			"expecting: identifier, variable, string",
			"expecting: '='",
			"expecting: '|', EOF",
			"expecting: ',', '|', EOF",
			"expecting: '+', '-'",
			"expecting: ',', '(', ')', '|', EOF",
			"expecting: ',', ')', '|', EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 2, 3, 4, 4, 5, 1, 6, 7, 8, 6, 8, 5, 8, 4, 9, 9, 1, 8, 10, 10, 11, 11, 10, 12, 8, 2, 2, 4, 13, 9, 8, 14, 15, 4, 9, 16, 17, 18, 19, 2, 4, 11, 20, 20, 21, 21, 11, 15, 4, 2, 4, 4, 17, 18, 17, 4, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
