/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AApproxMain extends PMain
{
    private TVariable _variable_;
    private TDefinedby _definedby_;
    private PEntitypattern _entitypattern_;

    public AApproxMain()
    {
        // Constructor
    }

    public AApproxMain(
        @SuppressWarnings("hiding") TVariable _variable_,
        @SuppressWarnings("hiding") TDefinedby _definedby_,
        @SuppressWarnings("hiding") PEntitypattern _entitypattern_)
    {
        // Constructor
        setVariable(_variable_);

        setDefinedby(_definedby_);

        setEntitypattern(_entitypattern_);

    }

    @Override
    public Object clone()
    {
        return new AApproxMain(
            cloneNode(this._variable_),
            cloneNode(this._definedby_),
            cloneNode(this._entitypattern_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAApproxMain(this);
    }

    public TVariable getVariable()
    {
        return this._variable_;
    }

    public void setVariable(TVariable node)
    {
        if(this._variable_ != null)
        {
            this._variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variable_ = node;
    }

    public TDefinedby getDefinedby()
    {
        return this._definedby_;
    }

    public void setDefinedby(TDefinedby node)
    {
        if(this._definedby_ != null)
        {
            this._definedby_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definedby_ = node;
    }

    public PEntitypattern getEntitypattern()
    {
        return this._entitypattern_;
    }

    public void setEntitypattern(PEntitypattern node)
    {
        if(this._entitypattern_ != null)
        {
            this._entitypattern_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entitypattern_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variable_)
            + toString(this._definedby_)
            + toString(this._entitypattern_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variable_ == child)
        {
            this._variable_ = null;
            return;
        }

        if(this._definedby_ == child)
        {
            this._definedby_ = null;
            return;
        }

        if(this._entitypattern_ == child)
        {
            this._entitypattern_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variable_ == oldChild)
        {
            setVariable((TVariable) newChild);
            return;
        }

        if(this._definedby_ == oldChild)
        {
            setDefinedby((TDefinedby) newChild);
            return;
        }

        if(this._entitypattern_ == oldChild)
        {
            setEntitypattern((PEntitypattern) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
