/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class ABodyOptdefinition extends POptdefinition
{
    private PEntitybody _entitybody_;

    public ABodyOptdefinition()
    {
        // Constructor
    }

    public ABodyOptdefinition(
        @SuppressWarnings("hiding") PEntitybody _entitybody_)
    {
        // Constructor
        setEntitybody(_entitybody_);

    }

    @Override
    public Object clone()
    {
        return new ABodyOptdefinition(
            cloneNode(this._entitybody_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABodyOptdefinition(this);
    }

    public PEntitybody getEntitybody()
    {
        return this._entitybody_;
    }

    public void setEntitybody(PEntitybody node)
    {
        if(this._entitybody_ != null)
        {
            this._entitybody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entitybody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._entitybody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._entitybody_ == child)
        {
            this._entitybody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._entitybody_ == oldChild)
        {
            setEntitybody((PEntitybody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
