/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AEntitypattern extends PEntitypattern
{
    private PEntitytype _entitytype_;
    private PEntitybody _entitybody_;

    public AEntitypattern()
    {
        // Constructor
    }

    public AEntitypattern(
        @SuppressWarnings("hiding") PEntitytype _entitytype_,
        @SuppressWarnings("hiding") PEntitybody _entitybody_)
    {
        // Constructor
        setEntitytype(_entitytype_);

        setEntitybody(_entitybody_);

    }

    @Override
    public Object clone()
    {
        return new AEntitypattern(
            cloneNode(this._entitytype_),
            cloneNode(this._entitybody_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEntitypattern(this);
    }

    public PEntitytype getEntitytype()
    {
        return this._entitytype_;
    }

    public void setEntitytype(PEntitytype node)
    {
        if(this._entitytype_ != null)
        {
            this._entitytype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entitytype_ = node;
    }

    public PEntitybody getEntitybody()
    {
        return this._entitybody_;
    }

    public void setEntitybody(PEntitybody node)
    {
        if(this._entitybody_ != null)
        {
            this._entitybody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entitybody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._entitytype_)
            + toString(this._entitybody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._entitytype_ == child)
        {
            this._entitytype_ = null;
            return;
        }

        if(this._entitybody_ == child)
        {
            this._entitybody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._entitytype_ == oldChild)
        {
            setEntitytype((PEntitytype) newChild);
            return;
        }

        if(this._entitybody_ == oldChild)
        {
            setEntitybody((PEntitybody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
