/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AIdEntity extends PEntity
{
    private PVartype _vartype_;

    public AIdEntity()
    {
        // Constructor
    }

    public AIdEntity(
        @SuppressWarnings("hiding") PVartype _vartype_)
    {
        // Constructor
        setVartype(_vartype_);

    }

    @Override
    public Object clone()
    {
        return new AIdEntity(
            cloneNode(this._vartype_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdEntity(this);
    }

    public PVartype getVartype()
    {
        return this._vartype_;
    }

    public void setVartype(PVartype node)
    {
        if(this._vartype_ != null)
        {
            this._vartype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vartype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vartype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vartype_ == child)
        {
            this._vartype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vartype_ == oldChild)
        {
            setVartype((PVartype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
