/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleQuery extends PQuery
{
    private PHead _head_;
    private TDefinedby _definedby_;
    private PBody _body_;

    public ASimpleQuery()
    {
        // Constructor
    }

    public ASimpleQuery(
        @SuppressWarnings("hiding") PHead _head_,
        @SuppressWarnings("hiding") TDefinedby _definedby_,
        @SuppressWarnings("hiding") PBody _body_)
    {
        // Constructor
        setHead(_head_);

        setDefinedby(_definedby_);

        setBody(_body_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleQuery(
            cloneNode(this._head_),
            cloneNode(this._definedby_),
            cloneNode(this._body_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleQuery(this);
    }

    public PHead getHead()
    {
        return this._head_;
    }

    public void setHead(PHead node)
    {
        if(this._head_ != null)
        {
            this._head_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._head_ = node;
    }

    public TDefinedby getDefinedby()
    {
        return this._definedby_;
    }

    public void setDefinedby(TDefinedby node)
    {
        if(this._definedby_ != null)
        {
            this._definedby_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._definedby_ = node;
    }

    public PBody getBody()
    {
        return this._body_;
    }

    public void setBody(PBody node)
    {
        if(this._body_ != null)
        {
            this._body_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._body_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._head_)
            + toString(this._definedby_)
            + toString(this._body_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._head_ == child)
        {
            this._head_ = null;
            return;
        }

        if(this._definedby_ == child)
        {
            this._definedby_ = null;
            return;
        }

        if(this._body_ == child)
        {
            this._body_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._head_ == oldChild)
        {
            setHead((PHead) newChild);
            return;
        }

        if(this._definedby_ == oldChild)
        {
            setDefinedby((TDefinedby) newChild);
            return;
        }

        if(this._body_ == oldChild)
        {
            setBody((PBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
