/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class ASinglePattern extends PPattern
{
    private PRequest _request_;

    public ASinglePattern()
    {
        // Constructor
    }

    public ASinglePattern(
        @SuppressWarnings("hiding") PRequest _request_)
    {
        // Constructor
        setRequest(_request_);

    }

    @Override
    public Object clone()
    {
        return new ASinglePattern(
            cloneNode(this._request_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASinglePattern(this);
    }

    public PRequest getRequest()
    {
        return this._request_;
    }

    public void setRequest(PRequest node)
    {
        if(this._request_ != null)
        {
            this._request_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._request_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._request_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._request_ == child)
        {
            this._request_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._request_ == oldChild)
        {
            setRequest((PRequest) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
