/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AVariableValue extends PValue
{
    private TVariable _variable_;
    private POptdefinition _optdefinition_;

    public AVariableValue()
    {
        // Constructor
    }

    public AVariableValue(
        @SuppressWarnings("hiding") TVariable _variable_,
        @SuppressWarnings("hiding") POptdefinition _optdefinition_)
    {
        // Constructor
        setVariable(_variable_);

        setOptdefinition(_optdefinition_);

    }

    @Override
    public Object clone()
    {
        return new AVariableValue(
            cloneNode(this._variable_),
            cloneNode(this._optdefinition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVariableValue(this);
    }

    public TVariable getVariable()
    {
        return this._variable_;
    }

    public void setVariable(TVariable node)
    {
        if(this._variable_ != null)
        {
            this._variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variable_ = node;
    }

    public POptdefinition getOptdefinition()
    {
        return this._optdefinition_;
    }

    public void setOptdefinition(POptdefinition node)
    {
        if(this._optdefinition_ != null)
        {
            this._optdefinition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optdefinition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variable_)
            + toString(this._optdefinition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variable_ == child)
        {
            this._variable_ = null;
            return;
        }

        if(this._optdefinition_ == child)
        {
            this._optdefinition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variable_ == oldChild)
        {
            setVariable((TVariable) newChild);
            return;
        }

        if(this._optdefinition_ == oldChild)
        {
            setOptdefinition((POptdefinition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
