/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class TDefined extends Token
{
    public TDefined()
    {
        super.setText(":-");
    }

    public TDefined(int line, int pos)
    {
        super.setText(":-");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDefined(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDefined(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDefined text.");
    }
}
