/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.analysis;

import entitiesdb.language.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseADefinitionQuery(ADefinitionQuery node);
    void caseARequest(ARequest node);
    void caseASingleAttributes(ASingleAttributes node);
    void caseAListAttributes(AListAttributes node);
    void caseAAtomicValuetype(AAtomicValuetype node);
    void caseAEntityValuetype(AEntityValuetype node);
    void caseAVarValuetype(AVarValuetype node);
    void caseAPatternBody(APatternBody node);
    void caseASinglePattern(ASinglePattern node);
    void caseAListPattern(AListPattern node);
    void caseAConditionsWithblock(AConditionsWithblock node);
    void caseAEmptyWithblock(AEmptyWithblock node);
    void caseASingleConditions(ASingleConditions node);
    void caseAListConditions(AListConditions node);

    void caseTNewLine(TNewLine node);
    void caseTBlank(TBlank node);
    void caseTComa(TComa node);
    void caseTColon(TColon node);
    void caseTDefined(TDefined node);
    void caseTLbracket(TLbracket node);
    void caseTRbracket(TRbracket node);
    void caseTIdentifier(TIdentifier node);
    void caseTVariable(TVariable node);
    void caseTString(TString node);
    void caseTWith(TWith node);
    void caseTEqual(TEqual node);
    void caseEOF(EOF node);
}
