/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AAttribute extends PAttribute
{
    private PAttributetype _attributetype_;
    private TColon _colon_;
    private PValue _value_;

    public AAttribute()
    {
        // Constructor
    }

    public AAttribute(
        @SuppressWarnings("hiding") PAttributetype _attributetype_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PValue _value_)
    {
        // Constructor
        setAttributetype(_attributetype_);

        setColon(_colon_);

        setValue(_value_);

    }

    @Override
    public Object clone()
    {
        return new AAttribute(
            cloneNode(this._attributetype_),
            cloneNode(this._colon_),
            cloneNode(this._value_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttribute(this);
    }

    public PAttributetype getAttributetype()
    {
        return this._attributetype_;
    }

    public void setAttributetype(PAttributetype node)
    {
        if(this._attributetype_ != null)
        {
            this._attributetype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributetype_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attributetype_)
            + toString(this._colon_)
            + toString(this._value_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attributetype_ == child)
        {
            this._attributetype_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attributetype_ == oldChild)
        {
            setAttributetype((PAttributetype) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
