/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AConditionsWithblock extends PWithblock
{
    private TWith _with_;
    private PConditions _conditions_;

    public AConditionsWithblock()
    {
        // Constructor
    }

    public AConditionsWithblock(
        @SuppressWarnings("hiding") TWith _with_,
        @SuppressWarnings("hiding") PConditions _conditions_)
    {
        // Constructor
        setWith(_with_);

        setConditions(_conditions_);

    }

    @Override
    public Object clone()
    {
        return new AConditionsWithblock(
            cloneNode(this._with_),
            cloneNode(this._conditions_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConditionsWithblock(this);
    }

    public TWith getWith()
    {
        return this._with_;
    }

    public void setWith(TWith node)
    {
        if(this._with_ != null)
        {
            this._with_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._with_ = node;
    }

    public PConditions getConditions()
    {
        return this._conditions_;
    }

    public void setConditions(PConditions node)
    {
        if(this._conditions_ != null)
        {
            this._conditions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditions_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._with_)
            + toString(this._conditions_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._with_ == child)
        {
            this._with_ = null;
            return;
        }

        if(this._conditions_ == child)
        {
            this._conditions_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._with_ == oldChild)
        {
            setWith((TWith) newChild);
            return;
        }

        if(this._conditions_ == oldChild)
        {
            setConditions((PConditions) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
