/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class ADifferentCondition extends PCondition
{
    private PValue _left_;
    private TDifferent _different_;
    private PValue _right_;

    public ADifferentCondition()
    {
        // Constructor
    }

    public ADifferentCondition(
        @SuppressWarnings("hiding") PValue _left_,
        @SuppressWarnings("hiding") TDifferent _different_,
        @SuppressWarnings("hiding") PValue _right_)
    {
        // Constructor
        setLeft(_left_);

        setDifferent(_different_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ADifferentCondition(
            cloneNode(this._left_),
            cloneNode(this._different_),
            cloneNode(this._right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADifferentCondition(this);
    }

    public PValue getLeft()
    {
        return this._left_;
    }

    public void setLeft(PValue node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TDifferent getDifferent()
    {
        return this._different_;
    }

    public void setDifferent(TDifferent node)
    {
        if(this._different_ != null)
        {
            this._different_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._different_ = node;
    }

    public PValue getRight()
    {
        return this._right_;
    }

    public void setRight(PValue node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._different_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._different_ == child)
        {
            this._different_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PValue) newChild);
            return;
        }

        if(this._different_ == oldChild)
        {
            setDifferent((TDifferent) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
