/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AElementAttribute extends PAttribute
{
    private PVartype _vartype_;
    private TColon _colon_;
    private PValue _value_;

    public AElementAttribute()
    {
        // Constructor
    }

    public AElementAttribute(
        @SuppressWarnings("hiding") PVartype _vartype_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PValue _value_)
    {
        // Constructor
        setVartype(_vartype_);

        setColon(_colon_);

        setValue(_value_);

    }

    @Override
    public Object clone()
    {
        return new AElementAttribute(
            cloneNode(this._vartype_),
            cloneNode(this._colon_),
            cloneNode(this._value_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementAttribute(this);
    }

    public PVartype getVartype()
    {
        return this._vartype_;
    }

    public void setVartype(PVartype node)
    {
        if(this._vartype_ != null)
        {
            this._vartype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vartype_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vartype_)
            + toString(this._colon_)
            + toString(this._value_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vartype_ == child)
        {
            this._vartype_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vartype_ == oldChild)
        {
            setVartype((PVartype) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
