/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyAttriblist extends PAttriblist
{

    public AEmptyAttriblist()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyAttriblist();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyAttriblist(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
