/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AListConditions extends PConditions
{
    private PConditions _conditions_;
    private TComa _coma_;
    private PValuetype _left_;
    private TEqual _equal_;
    private PValuetype _right_;

    public AListConditions()
    {
        // Constructor
    }

    public AListConditions(
        @SuppressWarnings("hiding") PConditions _conditions_,
        @SuppressWarnings("hiding") TComa _coma_,
        @SuppressWarnings("hiding") PValuetype _left_,
        @SuppressWarnings("hiding") TEqual _equal_,
        @SuppressWarnings("hiding") PValuetype _right_)
    {
        // Constructor
        setConditions(_conditions_);

        setComa(_coma_);

        setLeft(_left_);

        setEqual(_equal_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AListConditions(
            cloneNode(this._conditions_),
            cloneNode(this._coma_),
            cloneNode(this._left_),
            cloneNode(this._equal_),
            cloneNode(this._right_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListConditions(this);
    }

    public PConditions getConditions()
    {
        return this._conditions_;
    }

    public void setConditions(PConditions node)
    {
        if(this._conditions_ != null)
        {
            this._conditions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditions_ = node;
    }

    public TComa getComa()
    {
        return this._coma_;
    }

    public void setComa(TComa node)
    {
        if(this._coma_ != null)
        {
            this._coma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._coma_ = node;
    }

    public PValuetype getLeft()
    {
        return this._left_;
    }

    public void setLeft(PValuetype node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TEqual getEqual()
    {
        return this._equal_;
    }

    public void setEqual(TEqual node)
    {
        if(this._equal_ != null)
        {
            this._equal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._equal_ = node;
    }

    public PValuetype getRight()
    {
        return this._right_;
    }

    public void setRight(PValuetype node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conditions_)
            + toString(this._coma_)
            + toString(this._left_)
            + toString(this._equal_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conditions_ == child)
        {
            this._conditions_ = null;
            return;
        }

        if(this._coma_ == child)
        {
            this._coma_ = null;
            return;
        }

        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._equal_ == child)
        {
            this._equal_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conditions_ == oldChild)
        {
            setConditions((PConditions) newChild);
            return;
        }

        if(this._coma_ == oldChild)
        {
            setComa((TComa) newChild);
            return;
        }

        if(this._left_ == oldChild)
        {
            setLeft((PValuetype) newChild);
            return;
        }

        if(this._equal_ == oldChild)
        {
            setEqual((TEqual) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PValuetype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
