/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class AListAttributes extends PAttributes
{
    private PAttribute _attribute_;
    private TComa _coma_;
    private PAttributes _attributes_;

    public AListAttributes()
    {
        // Constructor
    }

    public AListAttributes(
        @SuppressWarnings("hiding") PAttribute _attribute_,
        @SuppressWarnings("hiding") TComa _coma_,
        @SuppressWarnings("hiding") PAttributes _attributes_)
    {
        // Constructor
        setAttribute(_attribute_);

        setComa(_coma_);

        setAttributes(_attributes_);

    }

    @Override
    public Object clone()
    {
        return new AListAttributes(
            cloneNode(this._attribute_),
            cloneNode(this._coma_),
            cloneNode(this._attributes_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListAttributes(this);
    }

    public PAttribute getAttribute()
    {
        return this._attribute_;
    }

    public void setAttribute(PAttribute node)
    {
        if(this._attribute_ != null)
        {
            this._attribute_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attribute_ = node;
    }

    public TComa getComa()
    {
        return this._coma_;
    }

    public void setComa(TComa node)
    {
        if(this._coma_ != null)
        {
            this._coma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._coma_ = node;
    }

    public PAttributes getAttributes()
    {
        return this._attributes_;
    }

    public void setAttributes(PAttributes node)
    {
        if(this._attributes_ != null)
        {
            this._attributes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attribute_)
            + toString(this._coma_)
            + toString(this._attributes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attribute_ == child)
        {
            this._attribute_ = null;
            return;
        }

        if(this._coma_ == child)
        {
            this._coma_ = null;
            return;
        }

        if(this._attributes_ == child)
        {
            this._attributes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attribute_ == oldChild)
        {
            setAttribute((PAttribute) newChild);
            return;
        }

        if(this._coma_ == oldChild)
        {
            setComa((TComa) newChild);
            return;
        }

        if(this._attributes_ == oldChild)
        {
            setAttributes((PAttributes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
