/* This file was generated by SableCC (http://www.sablecc.org/). */

package entitiesdb.language.node;

import entitiesdb.language.analysis.*;

@SuppressWarnings("nls")
public final class TDefinedby extends Token
{
    public TDefinedby()
    {
        super.setText(":-");
    }

    public TDefinedby(int line, int pos)
    {
        super.setText(":-");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDefinedby(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDefinedby(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDefinedby text.");
    }
}
